import type { SavedSpotKind } from "./saved-spot-kinds";

export type SavedSpotReservation =
  | "required"
  | "recommended"
  | "walk-in"
  | "not-needed";

export type SavedSpot = {
  id: string;
  name: string;
  address: string;
  lat: number;
  lng: number;
  kind: SavedSpotKind;
  note?: string;
  visited?: boolean;
  /** e.g. brunch, breakfast, matcha — used when filtering findNearbySpots */
  tags?: string[];
  /** Path under /public, e.g. /images/saved-spots/mitr-thai.png */
  photo?: string;
  cuisine?: string;
  mustOrder?: string[];
  bestFor?: string[];
  reservation?: SavedSpotReservation;
};

export const savedSpots: SavedSpot[] = [
  {
    id: "adda",
    name: "Adda",
    address: "107 1st Ave",
    lat: 40.7268472,
    lng: -73.986228,
    kind: "nice",
    visited: true,
    note: "I've already told you about this one, but must go if you're not tired of Indian food after Musaafer!",
    photo: "/images/saved-spots/adda.png",
    cuisine: "Indian (regional)",
    mustOrder: ["bheja masala", "baby goat biryani", "lamb parcha", "butter chicken experience"],
    bestFor: ["special occasion", "groups", "date night"],
    reservation: "recommended",
  },
  {
    id: "au-zaatar",
    name: "Au Za'atar",
    address: "188 Avenue A",
    lat: 40.7289381,
    lng: -73.9812454,
    kind: "casual",
    cuisine: "Lebanese",
    mustOrder: ["manoushe", "labneh", "shawarma platter"],
    bestFor: ["brunch", "casual hang", "groups"],
    reservation: "walk-in",
  },
  {
    id: "ayat",
    name: "Ayat",
    address: "107 Loisaida Ave",
    lat: 40.7242306,
    lng: -73.9789217,
    kind: "casual",
    cuisine: "Palestinian",
    mustOrder: ["musakhan", "knafeh", "hummus with meat"],
    bestFor: ["groups", "casual hang"],
    reservation: "recommended",
  },
  {
    id: "birdland",
    name: "Birdland",
    address: "315 W 44th St",
    lat: 40.7590853,
    lng: -73.9896379,
    kind: "bar",
    cuisine: "Jazz club",
    mustOrder: ["cover charge + cocktails"],
    bestFor: ["live music", "date night", "special occasion"],
    reservation: "required",
  },
  {
    id: "bleecker-street-pizza",
    name: "Bleecker Street Pizza",
    address: "69 7th Ave S",
    lat: 40.7317056,
    lng: -74.0037793,
    kind: "casual",
    cuisine: "Pizza",
    mustOrder: ["Nonna Maria slice", "Grandma slice"],
    bestFor: ["quick bite", "late night"],
    reservation: "walk-in",
  },
  {
    id: "brooklyn-bridge",
    name: "Brooklyn Bridge",
    address: "Brooklyn Bridge",
    lat: 40.7062175,
    lng: -73.9970208,
    kind: "activity",
    visited: true,
    cuisine: "Landmark",
    bestFor: ["sightseeing", "casual hang"],
    reservation: "not-needed",
  },
  {
    id: "by-antidote",
    name: "By Antidote",
    address: "30 E 20th St",
    lat: 40.7385926,
    lng: -73.988887,
    kind: "nice",
    cuisine: "Sichuan",
    mustOrder: ["century egg with burrata", "dan dan noodles", "mapo tofu"],
    bestFor: ["date night", "groups"],
    reservation: "recommended",
  },
  {
    id: "7th-st-burger",
    name: "7th Street Burger",
    address: "91 E 7th St",
    lat: 40.7269803,
    lng: -73.9854205,
    kind: "casual",
    visited: true,
    photo: "/images/saved-spots/7th-st-burger.png",
    cuisine: "Burgers",
    mustOrder: ["double cheeseburger", "crinkle fries"],
    bestFor: ["quick bite", "late night"],
    reservation: "walk-in",
  },
  {
    id: "c-and-b",
    name: "C&B",
    address: "178 E 7th St",
    lat: 40.7250538,
    lng: -73.9816964,
    kind: "cafe",
    tags: ["brunch"],
    cuisine: "Café (Australian-inspired)",
    mustOrder: ["avocado toast", "flat white"],
    bestFor: ["brunch", "solo"],
    reservation: "walk-in",
  },
  {
    id: "cava",
    name: "CAVA",
    address: "708 3rd Ave",
    lat: 40.7522516,
    lng: -73.9736217,
    kind: "casual",
    visited: true,
    cuisine: "Mediterranean (fast-casual)",
    mustOrder: ["greens + grains bowl", "spicy lamb meatballs"],
    bestFor: ["quick bite", "solo", "lunch"],
    reservation: "walk-in",
  },
  {
    id: "cafe-maud",
    name: "Cafe Maud",
    address: "132 2nd Ave",
    lat: 40.7286121,
    lng: -73.9874271,
    kind: "nice",
    visited: true,
    tags: ["brunch"],
    note: "Cute Australian brunch spot with great food + near Shobha's!",
    cuisine: "Australian brunch",
    mustOrder: ["big breakfast", "flat white", "banana bread"],
    bestFor: ["brunch", "date night"],
    reservation: "recommended",
  },
  {
    id: "cafe-mogador",
    name: "Cafe Mogador",
    address: "101 St Marks Pl",
    lat: 40.7274166,
    lng: -73.9843381,
    kind: "casual",
    tags: ["brunch"],
    cuisine: "Moroccan / Mediterranean",
    mustOrder: ["Moroccan eggs", "Mogador salad", "tagine"],
    bestFor: ["brunch", "casual hang", "groups"],
    reservation: "walk-in",
  },
  {
    id: "caffe-panna-irving",
    name: "Caffè Panna",
    address: "77 Irving Pl",
    lat: 40.7369641,
    lng: -73.9868018,
    kind: "cafe",
    visited: true,
    cuisine: "Italian gelato & coffee",
    mustOrder: ["affogato", "seasonal gelato scoop"],
    bestFor: ["solo", "quick bite", "dessert"],
    reservation: "walk-in",
  },
  {
    id: "casa-mono",
    name: "Casa Mono and Bar Jamón",
    address: "52 Irving Pl",
    lat: 40.7359257,
    lng: -73.9871655,
    kind: "nice",
    cuisine: "Spanish tapas",
    mustOrder: ["croquetas", "foie gras with membrillo", "pulpo"],
    bestFor: ["date night", "groups"],
    reservation: "recommended",
  },
  {
    id: "chama-mama",
    name: "Chama Mama",
    address: "149 W 14th St",
    lat: 40.7384827,
    lng: -73.9988578,
    kind: "casual",
    cuisine: "Georgian",
    mustOrder: ["adjarian khachapuri", "khinkali", "pkhali spread"],
    bestFor: ["groups", "date night", "brunch"],
    reservation: "recommended",
  },
  {
    id: "chili",
    name: "CHILI",
    address: "13 E 37th St",
    lat: 40.7501079,
    lng: -73.9820782,
    kind: "nice",
    visited: true,
    note: "Solo dined here a lot when I was living near Grand Central. Not as cute because it's in Midtown, but great schezuan food",
    cuisine: "Sichuan",
    mustOrder: ["dan dan noodles", "mapo tofu", "dry pot"],
    bestFor: ["solo", "lunch", "groups"],
    reservation: "walk-in",
  },
  {
    id: "devocion",
    name: "Devoción",
    address: "25 E 20th St",
    lat: 40.7391158,
    lng: -73.9891065,
    kind: "cafe",
    cuisine: "Colombian coffee",
    mustOrder: ["pour-over", "cortado"],
    bestFor: ["solo", "quick bite"],
    reservation: "walk-in",
  },
  {
    id: "fairfax",
    name: "Fairfax",
    address: "234 W 4th St",
    lat: 40.7343436,
    lng: -74.0031007,
    kind: "casual",
    tags: ["brunch"],
    cuisine: "American brunch",
    mustOrder: ["breakfast sandwich", "sourdough pancakes", "burrata toast"],
    bestFor: ["brunch", "date night"],
    reservation: "recommended",
  },
  {
    id: "fish-cheeks",
    name: "Fish Cheeks",
    address: "55 Bond St",
    lat: 40.7257377,
    lng: -73.9927035,
    kind: "nice",
    cuisine: "Thai seafood",
    mustOrder: ["coconut crab curry", "zabb chicken wings", "whole steamed fish"],
    bestFor: ["date night", "groups"],
    reservation: "recommended",
  },
  {
    id: "fumo-kips-bay",
    name: "Fumo Kips Bay",
    address: "415 Third Ave",
    lat: 40.742602,
    lng: -73.9801487,
    kind: "nice",
    cuisine: "Italian",
    mustOrder: ["truffle tagliolini", "wood-fired pizza", "burrata"],
    bestFor: ["date night", "groups"],
    reservation: "recommended",
  },
  {
    id: "gotan",
    name: "Gotan",
    address: "130 Franklin St",
    lat: 40.7192553,
    lng: -74.0066082,
    kind: "cafe",
    visited: true,
    tags: ["brunch"],
    cuisine: "Specialty coffee & café",
    mustOrder: ["avocado feta toast", "cortado", "grain bowl"],
    bestFor: ["brunch", "solo", "quick bite"],
    reservation: "walk-in",
  },
  {
    id: "indian-accent",
    name: "Indian Accent",
    address: "123 W 56th St",
    lat: 40.7640192,
    lng: -73.9783492,
    kind: "nice",
    cuisine: "Indian (fine dining)",
    mustOrder: ["blue cheese naan", "tasting menu", "meetha achaar pork ribs"],
    bestFor: ["special occasion", "date night"],
    reservation: "required",
  },
  {
    id: "natural-history-museum",
    name: "Natural History Museum",
    address: "200 Central Park W",
    lat: 40.7811007,
    lng: -73.9742362,
    kind: "activity",
    cuisine: "Museum",
    mustOrder: ["Rose Center / Hayden Planetarium", "dinosaur halls"],
    bestFor: ["sightseeing", "groups", "families"],
    reservation: "recommended",
  },
  {
    id: "janie-baked-goods",
    name: "Janie's Life Changing Baked Goods",
    address: "212 W 80th St",
    lat: 40.7840334,
    lng: -73.9788663,
    kind: "cafe",
    cuisine: "Bakery (gluten-free)",
    mustOrder: ["chocolate chip cookie", "brownie"],
    bestFor: ["quick bite", "solo"],
    reservation: "walk-in",
  },
  {
    id: "jazba",
    name: "Jazba",
    address: "207 Second Ave",
    lat: 40.7316574,
    lng: -73.9856935,
    kind: "nice",
    cuisine: "Indian (regional)",
    mustOrder: ["biryani", "kebabs", "chaat"],
    bestFor: ["date night", "groups"],
    reservation: "recommended",
  },
  {
    id: "joseph-leonard",
    name: "Joseph Leonard",
    address: "170 Waverly Pl",
    lat: 40.7335936,
    lng: -74.0016502,
    kind: "casual",
    tags: ["brunch"],
    cuisine: "American (West Village)",
    mustOrder: ["chocolate chip pancake", "griddled corn bread", "market salad"],
    bestFor: ["brunch", "casual hang"],
    reservation: "walk-in",
  },
  {
    id: "kikis",
    name: "Kiki's",
    address: "130 Division St",
    lat: 40.7145315,
    lng: -73.9919097,
    kind: "casual",
    cuisine: "Greek",
    mustOrder: ["saganaki", "grilled octopus", "Greek salad"],
    bestFor: ["casual hang", "groups", "date night"],
    reservation: "walk-in",
  },
  {
    id: "la-cabra",
    name: "La Cabra",
    address: "152 2nd Ave",
    lat: 40.7293547,
    lng: -73.9866878,
    kind: "cafe",
    visited: true,
    cuisine: "Coffee & Danish bakery",
    mustOrder: ["cardamom bun", "cortado"],
    bestFor: ["solo", "quick bite", "breakfast"],
    reservation: "walk-in",
  },
  {
    id: "levain-lafayette",
    name: "Levain Bakery",
    address: "340 Lafayette St",
    lat: 40.7262725,
    lng: -73.9946961,
    kind: "cafe",
    cuisine: "Bakery (cookies)",
    mustOrder: ["chocolate chip walnut cookie", "dark chocolate cookie"],
    bestFor: ["quick bite", "dessert"],
    reservation: "walk-in",
  },
  {
    id: "levain-18th",
    name: "Levain Bakery",
    address: "2 W 18th St",
    lat: 40.7386759,
    lng: -73.9924807,
    kind: "cafe",
    cuisine: "Bakery (cookies)",
    mustOrder: ["chocolate chip walnut cookie", "dark chocolate cookie"],
    bestFor: ["quick bite", "dessert"],
    reservation: "walk-in",
  },
  {
    id: "locanda-verde",
    name: "Locanda Verde",
    address: "377 Greenwich St",
    lat: 40.7198779,
    lng: -74.010019,
    kind: "nice",
    cuisine: "Italian",
    mustOrder: ["sheep's milk ricotta", "lamb ragu", "two-layer lasagna"],
    bestFor: ["special occasion", "date night", "brunch"],
    reservation: "required",
  },
  {
    id: "lindustrie",
    name: "L'industrie Pizzeria",
    address: "104 Christopher St",
    lat: 40.7332057,
    lng: -74.0049379,
    kind: "casual",
    visited: true,
    note: "Supposedly the best slice in NYC although I think it's overrated after waiting in an hour line lol",
    cuisine: "Pizza (Neapolitan-style slices)",
    mustOrder: ["burrata slice", "pepperoni slice"],
    bestFor: ["quick bite", "casual hang"],
    reservation: "walk-in",
  },
  {
    id: "little-collins",
    name: "Little Collins",
    address: "708 3rd Ave",
    lat: 40.7523935,
    lng: -73.9735028,
    kind: "cafe",
    visited: true,
    tags: ["brunch"],
    cuisine: "Australian café",
    mustOrder: ["avocado toast", "flat white", "breakfast bowl"],
    bestFor: ["brunch", "solo", "quick bite"],
    reservation: "walk-in",
  },
  {
    id: "love-mama",
    name: "Love Mama",
    address: "174 2nd Ave",
    lat: 40.7304045,
    lng: -73.9861256,
    kind: "casual",
    visited: true,
    cuisine: "Japanese",
    mustOrder: ["shoyu ramen", "fried chicken", "spicy miso ramen"],
    bestFor: ["casual hang", "quick bite", "solo"],
    reservation: "walk-in",
  },
  {
    id: "marea",
    name: "Marea",
    address: "240 Central Park S",
    lat: 40.7673344,
    lng: -73.9811711,
    kind: "nice",
    cuisine: "Italian seafood",
    mustOrder: ["crudo tasting", "lobster burrata", "risotto ai frutti di mare"],
    bestFor: ["special occasion", "date night"],
    reservation: "required",
  },
  {
    id: "magnolia-bakery",
    name: "Magnolia Bakery",
    address: "1794 Broadway",
    lat: 40.7672083,
    lng: -73.9814833,
    kind: "cafe",
    visited: true,
    cuisine: "Bakery (American)",
    mustOrder: ["banana pudding", "red velvet cupcake"],
    bestFor: ["quick bite", "dessert"],
    reservation: "walk-in",
  },
  {
    id: "manjul",
    name: "Manjul",
    address: "31 Howard St",
    lat: 40.71954,
    lng: -74.00079,
    kind: "cafe",
    visited: true,
    photo: "/images/saved-spots/manjul.png",
    cuisine: "Indian café & sweets",
    mustOrder: ["masala chai", "samosa", "mithai box"],
    bestFor: ["solo", "quick bite"],
    reservation: "walk-in",
  },
  {
    id: "mitr-thai",
    name: "Mitr Thai",
    address: "37 W 46th St",
    lat: 40.7568723,
    lng: -73.9804251,
    kind: "nice",
    visited: true,
    note: "This is where I went with Pranav and it was excellent. Highly recommend getting a drink here too",
    photo: "/images/saved-spots/mitr-thai.png",
    cuisine: "Thai (regional)",
    mustOrder: ["gai gor lae", "crab fried rice", "tom yum", "roti massaman"],
    bestFor: ["date night", "pre-theater", "groups"],
    reservation: "recommended",
  },
  {
    id: "nolita-pizza",
    name: "Nolita Pizza",
    address: "68 Kenmare St",
    lat: 40.7209123,
    lng: -73.9961959,
    kind: "casual",
    cuisine: "Pizza",
    mustOrder: ["grandma slice", "vodka slice"],
    bestFor: ["quick bite", "late night"],
    reservation: "walk-in",
  },
  {
    id: "nom-wah",
    name: "Nom Wah",
    address: "10 Kenmare St",
    lat: 40.7203696,
    lng: -73.9945824,
    kind: "casual",
    tags: ["brunch"],
    cuisine: "Dim sum",
    mustOrder: ["har gow", "sesame ball", "rice roll"],
    bestFor: ["brunch", "groups", "casual hang"],
    reservation: "walk-in",
  },
  {
    id: "prince-st-pizza",
    name: "Prince St. Pizza",
    address: "27 Prince St",
    lat: 40.7230823,
    lng: -73.9945374,
    kind: "casual",
    visited: true,
    photo: "/images/saved-spots/prince-st-pizza.png",
    cuisine: "Pizza",
    mustOrder: ["spicy spring slice", "pepperoni square"],
    bestFor: ["quick bite", "late night"],
    reservation: "walk-in",
  },
  {
    id: "ramen-ishida",
    name: "Ramen Ishida",
    address: "122 Ludlow St",
    lat: 40.7195965,
    lng: -73.9883524,
    kind: "casual",
    cuisine: "Ramen (Hokkaido-style)",
    mustOrder: ["shoyu ramen", "tsukemen", "chashu rice"],
    bestFor: ["solo", "quick bite", "late night"],
    reservation: "walk-in",
  },
  {
    id: "santo-taco",
    name: "Santo Taco",
    address: "94 University Pl",
    lat: 40.7338821,
    lng: -73.9930035,
    kind: "casual",
    cuisine: "Mexican (tacos)",
    mustOrder: ["al pastor taco", "carne asada taco", "elote"],
    bestFor: ["casual hang", "quick bite", "groups"],
    reservation: "walk-in",
  },
  {
    id: "sappe",
    name: "Sappe",
    address: "240 W 14th St",
    lat: 40.7391677,
    lng: -74.0017632,
    kind: "casual",
    cuisine: "Thai (Isaan / Northern)",
    mustOrder: ["larb", "papaya salad", "sai krok Isaan"],
    bestFor: ["date night", "groups"],
    reservation: "recommended",
  },
  {
    id: "serafina",
    name: "Serafina",
    address: "241 Madison Ave",
    lat: 40.7500156,
    lng: -73.9811517,
    kind: "nice",
    visited: true,
    cuisine: "Italian",
    mustOrder: ["truffled tagliolini", "margherita pizza", "tiramisu"],
    bestFor: ["date night", "groups", "business lunch"],
    reservation: "recommended",
  },
  {
    id: "singlish",
    name: "Singlish",
    address: "17 E 13th St",
    lat: 40.7349936,
    lng: -73.993015,
    kind: "bar",
    cuisine: "Sri Lankan bar food",
    mustOrder: ["kottu roti", "hoppers", "arrack cocktail"],
    bestFor: ["drinks", "late night", "groups"],
    reservation: "walk-in",
  },
  {
    id: "soothr",
    name: "Soothr",
    address: "204 E 13th St",
    lat: 40.7322692,
    lng: -73.9873518,
    kind: "nice",
    cuisine: "Thai (Central)",
    mustOrder: ["koong karee", "khao soi", "ba mii pu"],
    bestFor: ["date night", "groups"],
    reservation: "recommended",
  },
  {
    id: "the-high-line",
    name: "The High Line",
    address: "820 Washington St",
    lat: 40.7397293,
    lng: -74.0082119,
    kind: "activity",
    visited: true,
    cuisine: "Park / elevated walkway",
    bestFor: ["sightseeing", "casual hang", "date night"],
    reservation: "not-needed",
  },
  {
    id: "the-odeon",
    name: "The Odeon",
    address: "145 W Broadway",
    lat: 40.7169082,
    lng: -74.0079209,
    kind: "nice",
    cuisine: "American bistro (French-influenced)",
    mustOrder: ["steak frites", "Odeon burger", "lobster bisque"],
    bestFor: ["date night", "special occasion", "late night"],
    reservation: "recommended",
  },
  {
    id: "thisbowl-nyc",
    name: "Thisbowl NYC",
    address: "65 Bleecker St",
    lat: 40.7263784,
    lng: -73.9949921,
    kind: "casual",
    photo: "/images/saved-spots/thisbowl-nyc.png",
    cuisine: "Healthy bowls",
    mustOrder: ["build-your-own bowl", "green goddess dressing"],
    bestFor: ["quick bite", "solo", "lunch"],
    reservation: "walk-in",
  },
  {
    id: "tomi-jazz",
    name: "Tomi Jazz",
    address: "239 E 53rd St",
    lat: 40.7572284,
    lng: -73.9677693,
    kind: "bar",
    cuisine: "Japanese izakaya & jazz bar",
    mustOrder: ["karaage", "sake", "yakitori"],
    bestFor: ["live music", "date night", "late night"],
    reservation: "walk-in",
  },
  {
    id: "uluh",
    name: "uluh",
    address: "152 Second Ave",
    lat: 40.7294457,
    lng: -73.9868292,
    kind: "nice",
    visited: true,
    note: "Insane dan dan noodles",
    photo: "/images/saved-spots/uluh.png",
    cuisine: "Sichuan",
    mustOrder: ["dan dan noodles", "peking duck", "spicy wontons"],
    bestFor: ["date night", "groups"],
    reservation: "recommended",
  },
  {
    id: "village-east",
    name: "Village East by Angelika",
    address: "181-189 Second Ave",
    lat: 40.7292,
    lng: -73.9858,
    kind: "activity",
    cuisine: "Art-house cinema",
    bestFor: ["date night", "casual hang"],
    reservation: "recommended",
  },
  {
    id: "wayan",
    name: "Wayan",
    address: "20 Spring St",
    lat: 40.7212142,
    lng: -73.9951519,
    kind: "nice",
    visited: true,
    cuisine: "Indonesian (French-influenced)",
    mustOrder: ["lobster noodles", "charred chicken lombok", "satay"],
    bestFor: ["date night", "special occasion", "groups"],
    reservation: "recommended",
  },
  {
    id: "win-son-bakery",
    name: "Win Son Bakery",
    address: "23 2nd Ave",
    lat: 40.7246056,
    lng: -73.9909301,
    kind: "cafe",
    tags: ["brunch"],
    cuisine: "Taiwanese-American bakery",
    mustOrder: ["scallion pancake sandwich", "doughnuts", "breakfast sandwich"],
    bestFor: ["brunch", "quick bite", "solo"],
    reservation: "walk-in",
  },
];
