export type NytRecipe = {
  title: string;
  href: string;
};

export const nytRecipes: NytRecipe[] = [
  { title: "Spicy Cottage Cheese Pasta Alla Vodka", href: "https://cooking.nytimes.com/recipes/786125287-spicy-cottage-cheese-pasta-alla-vodka" },
  { title: "Peanut Noodles With Spicy Tofu", href: "https://cooking.nytimes.com/recipes/776534758-peanut-noodles-with-spicy-tofu" },
  { title: "Chicken-Zucchini Meatballs With Feta", href: "https://cooking.nytimes.com/recipes/1021328-chicken-zucchini-meatballs-with-feta" },
  { title: "Chicken Tikka Masala", href: "https://cooking.nytimes.com/recipes/1019043-chicken-tikka-masala" },
  { title: "Sesame Soy Chicken With Ginger-Scallion Noodles", href: "https://cooking.nytimes.com/recipes/786382737-sesame-soy-chicken-with-ginger-scallion-noodles" },
  { title: "Lemony White Bean Soup With Turkey and Greens", href: "https://cooking.nytimes.com/recipes/1021776-lemony-white-bean-soup-with-turkey-and-greens" },
  { title: "Original Plum Torte", href: "https://cooking.nytimes.com/recipes/3783-original-plum-torte" },
  { title: "Classic Shrimp Scampi", href: "https://cooking.nytimes.com/recipes/9101-classic-shrimp-scampi" },
  { title: "Roasted Tomato and White Bean Stew", href: "https://cooking.nytimes.com/recipes/1020926-roasted-tomato-and-white-bean-stew" },
  { title: "Turkey Chili", href: "https://cooking.nytimes.com/recipes/7985-turkey-chili" },
  { title: "Shakshuka With Feta", href: "https://cooking.nytimes.com/recipes/1014721-shakshuka-with-feta" },
  { title: "Cheesy White Bean-Tomato Bake", href: "https://cooking.nytimes.com/recipes/1019681-cheesy-white-bean-tomato-bake" },
  { title: "Seared Zucchini and Halloumi in Red-Wine Vinaigrette", href: "https://cooking.nytimes.com/recipes/779127092-seared-zucchini-and-halloumi-in-red-wine-vinaigrette" },
  { title: "Elotes (Grilled Corn With Cheese, Lime and Chile)", href: "https://cooking.nytimes.com/recipes/1018269-elotes-grilled-corn-with-cheese-lime-and-chile" },
  { title: "Grilled Corn Panzanella", href: "https://cooking.nytimes.com/recipes/1025570-grilled-corn-panzanella" },
  { title: "Grilled Corn and Avocado Salad With Feta Dressing", href: "https://cooking.nytimes.com/recipes/1020403-grilled-corn-and-avocado-salad-with-feta-dressing" },
  { title: "Chicken, Eggplant and Basil Stir-Fry", href: "https://cooking.nytimes.com/recipes/784903295-chicken-eggplant-and-basil-stir-fry" },
  { title: "Green Goddess Chickpea Sauté", href: "https://cooking.nytimes.com/recipes/769116490-green-goddess-chickpea-saute" },
  { title: "Anda Bhurji (Tomato-Chile Scrambled Eggs)", href: "https://cooking.nytimes.com/recipes/776107352-anda-bhurji-tomato-chile-scrambled-eggs" },
  { title: "Crispy Tofu Nuggets", href: "https://cooking.nytimes.com/recipes/767029318-crispy-tofu-nuggets" },
  { title: "Crunchy Queso Wrap", href: "https://cooking.nytimes.com/recipes/1027001-crunchy-queso-wrap" },
  { title: "Indian-ish Nachos With Cheddar, Black Beans and Chutney", href: "https://cooking.nytimes.com/recipes/1020450-indian-ish-nachos-with-cheddar-black-beans-and-chutney" },
  { title: "Crispy Sheet-Pan Noodles With Glazed Tofu", href: "https://cooking.nytimes.com/recipes/1022637-crispy-sheet-pan-noodles-with-glazed-tofu" },
  { title: "Crisp Kale Chips With Chile and Lime", href: "https://cooking.nytimes.com/recipes/12152-crisp-kale-chips-with-chile-and-lime" },
  { title: "Fresh Corn and Black Bean Salad With Corn Chips", href: "https://cooking.nytimes.com/recipes/1027095-fresh-corn-and-black-bean-salad-with-corn-chips" },
  { title: "Fruit Crumble", href: "https://cooking.nytimes.com/recipes/1025182-fruit-crumble" },
  { title: "Zucchini Fritters", href: "https://cooking.nytimes.com/recipes/1025529-zucchini-fritters" },
  { title: "Buttery Peach and Ricotta Crostini", href: "https://cooking.nytimes.com/recipes/783544007-buttery-peach-and-ricotta-crostini" },
  { title: "Sweet Potato Fries", href: "https://cooking.nytimes.com/recipes/1014647-sweet-potato-fries" },
  { title: "Chicken Lo Mein", href: "https://cooking.nytimes.com/recipes/1026362-chicken-lo-mein" },
  { title: "Mango Lime Loaf Cake", href: "https://cooking.nytimes.com/recipes/1025983-mango-lime-loaf-cake" },
  { title: "Garlic Bread Grilled Cheese", href: "https://cooking.nytimes.com/recipes/783001839-garlic-bread-grilled-cheese" },
  { title: "Zucchini With Shallots", href: "https://cooking.nytimes.com/recipes/9529-zucchini-with-shallots" },
  { title: "Zucchini Butter Pasta", href: "https://cooking.nytimes.com/recipes/1027237-zucchini-butter-pasta" },
  { title: "Spicy Marmalade Chicken and Sweet Potatoes", href: "https://cooking.nytimes.com/recipes/1027725-spicy-marmalade-chicken-and-sweet-potatoes" },
  { title: "One-Pot French Onion Rigatoni", href: "https://cooking.nytimes.com/recipes/769539003-french-onion-rigatoni" },
  { title: "One-Pot Cheddar Tomato Mac", href: "https://cooking.nytimes.com/recipes/770764080-one-pot-cheddar-tomato-mac" },
  { title: "Seared Sweet Potatoes With Chermoula", href: "https://cooking.nytimes.com/recipes/1027618-seared-sweet-potatoes-with-chermoula" },
  { title: "Chicken and Pesto Rice With Peas", href: "https://cooking.nytimes.com/recipes/773766928-chicken-and-pesto-rice-with-peas" },
  { title: "Tofu and Sweet Potato Peanut Butter Curry", href: "https://cooking.nytimes.com/recipes/767371284-tofu-and-sweet-potato-peanut-butter-curry" },
  { title: "Chickpeas al Limone With Burrata", href: "https://cooking.nytimes.com/recipes/768413295-chickpeas-al-limone-with-burrata" },
  { title: "Wolfgang Puck’s Chicken Potpie", href: "https://cooking.nytimes.com/recipes/1027737-wolfgang-pucks-chicken-potpie" },
  { title: "Creamy Cottage Cheese Basil Pasta", href: "https://cooking.nytimes.com/recipes/774974792-creamy-cottage-cheese-basil-pasta" },
  { title: "Chicken and White Bean Stew", href: "https://cooking.nytimes.com/recipes/767821616-chicken-and-white-bean-stew" },
  { title: "Spinach Egg Bites", href: "https://cooking.nytimes.com/recipes/1027633-spinach-egg-bites" },
  { title: "One-Pot Cheesy Orecchiette With Cabbage and Paprika", href: "https://cooking.nytimes.com/recipes/1027439-one-pot-cheesy-orecchiette-with-cabbage-and-paprika" },
  { title: "Jake and Maggie Gyllenhaal’s Banana Bread", href: "https://cooking.nytimes.com/recipes/773329801-maggie-and-jake-gyllenhaals-banana-bread" },
  { title: "One-Pan Dumplings With Greens", href: "https://cooking.nytimes.com/recipes/776879603-one-pan-dumplings-with-greens" },
  { title: "Egg and Cheese Quesadilla", href: "https://cooking.nytimes.com/recipes/774974663-egg-and-cheese-quesadilla" },
  { title: "Dan Dan Noodles", href: "https://cooking.nytimes.com/recipes/1027503-dan-dan-noodles" },
  { title: "Chile Oil Dumplings With Noodles", href: "https://cooking.nytimes.com/recipes/782498213-chile-oil-dumplings-with-noodles" },
  { title: "Mushroom Smash Burgers", href: "https://cooking.nytimes.com/recipes/1025333-mushroom-smash-burgers" },
  { title: "Black Bean Burgers", href: "https://cooking.nytimes.com/recipes/12221-black-bean-burgers" },
  { title: "Easy Buttermilk Peach Cobbler", href: "https://cooking.nytimes.com/recipes/1025843-easy-buttermilk-peach-cobbler" },
];
